# Generated by Django 3.2.25 on 2025-11-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_timer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timer',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='timer',
            name='start_time',
        ),
        migrations.AddField(
            model_name='timer',
            name='last_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='timer',
            name='total_time',
            field=models.DateTimeField(default=None),
        ),
    ]
